# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ... (HW7)
author: Group 20 (Michael Milazzo, Jacob Jossart, and Kaichi Inoue)
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' # force


# Information about where the book exists on the web
repository:
  url: https://github.com/UCB-stat-159-s22/hw07-group20
  branch: main

# Add GitHub buttons to your book
html:
  use_repository_button: true

launch_buttons:
  binderhub_html: https://mybinder.org/v2/gh/UCB-stat-159-s22/hw07-group20/HEAD?labpath=main.ipynb
