name: cesm
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - IPython
  - ipykernel
  - numpy
  - pandas
  - dask
  - xarray=2022.3.0
  - zarr
  - gcsfs=2022.3.0
  - cartopy
  - nc-time-axis
  - matplotlib
  - seaborn
  - scipy
  - pip
  - pip:
    - cftime
    - ghp-import
    # - cesm
    - jupyter-book==0.12.3
    - jupyter-sphinx==0.3.2
    - markdown-it-py==1.1.0
    - markupsafe==2.1.1
    - myst-nb==0.13.2
    - myst-parser==0.15.2
    - sphinx==4.5.0
    - sphinx-jupyterbook-latex==0.4.6