name: cesm
channels:
  - conda-forge
dependencies:
  - python # =3.10
  - IPython
  - ipykernel
  - numpy
  - pandas
  - dask
  - xarray
  - zarr
  - lzo
  - gcsfs
  - cartopy
  - nc-time-axis
  - matplotlib
  - seaborn
  - scipy
  - pip:
    - cftime
