name: cesm
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - IPython
  - ipykernel
  - numpy
  - pandas
  - dask
  - xarray=2022.3.0
  - zarr
  - lzo
  - gcsfs=2022.3.0
  - cartopy
  - nc-time-axis
  - matplotlib
  - seaborn
  - scipy
  - pip:
    - cftime
